# build pkg

name: Build

permissions: write-all

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:bookworm
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: |
        apt-get update -y
        mkdir -p build/
        mv ./*.{cpp, qml, txt, desktop, qrc, h} build/ && mv {debian, images, translations} build/
    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    - name: Install build dependencies
      run: |
        mk-build-deps -i -t "apt-get --yes" -r
        cd build/
    - name: Fix KF5
      run: mkdir -p /usr/include/KF5
    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 1.9.9-20
        release_name: Release 1.9.9-20
        draft: false
        prerelease: false
    - name: Release
      uses: actions/upload-release-asset@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          lingmo-updator_1.9.9-20_amd64.deb
          lingmo-updator-dbgsym_1.9.9-20_amd64.deb
          lingmo-updator_1.9.9-20_amd64.buildinfo
          lingmo-updator_1.9.9-20_amd64.changes
