name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:bookworm
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: apt-get update -y
    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r
    - name: Fix KF5
      run: mkdir -p /usr/include/KF5
    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
         The release
        draft: false
        prerelease: false
